---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secret
  namespace: whoapp
spec:
  encryptedData:
    password: AgCPRoy4IfiDgDTb886wymkh2JmwADmryv5WWbakHlJwt9yf9ImhidLGREGtZfI0A0OuxocSWopGcr84SZt9JSyeTbrs9l5Lc10Nz0rSdN7dxWspl2Nh/1lLon1fVhXsjKv8/9Vq0+UYa3xV08/GU7TwFywsAuSKonvDTITXtZ6GuxTaPwm+EGwu1viO8ZTvGyP1grvx6ih9/o8pSF76CzpAlPGUUKA5RG3gPrMGtP+GwJzhNEwOBusX7tcbpnc/6vq3o6z+wxlrlWvDaUwC0pgkXyRZjGX5KCnxhIwIkxTRhvNY06a+3hjlBJTI/6oO5p+IZTwAzmn5HylY3+Z+7eA0xSZzLZ85BxxUKuvlxXl2HPldgNxbIJmXA1MZAmJj5Y57CmJSKLaFvQ7algdgJ2IJiaRUPi2w8OF/qJgSizjX83ynAxm1yfHUfRnLq2fCdFqAusueBezh7RE+H9TJM1/jpjGfiN6O+w1fJtmFxHYY4HYztjz1+0c4IDQUmUcALu2EfmN38uCCaWTv/u1OKlYW7F3/elLxTyko7LSGPX6InMgW1a/cGNb5DgLVKt7Rs/wGW16gwxQljwXPhxgZiBDVLAi7ndMjWlFwP+En5YOOszATuHmaJDpdw1h4vTaRSP/FgD/edagS7Bo5pQOackNElUsowiEC6hrch0llklFh/nBz3XfrkejI5M9sOXQMENSKClNE14m6Dw==
    username: AgAX/IYRrJ1HASn3Ib0WBrczGmys5gYjoR883d9MIWD1GEdXOvdQXCqbZ2do9W5og/3TtRQfcahnUZ8U/XBCV0vU0drfZSIxvIZIrz+N2+9fzQWV+S2zymwS3g2T3LOHrewSao8eVbPhsKOo06e7NorakoRFr+xxYH/Z0VQq9gA79EYeEVOt9xjNd8NZF5sGRiVyVlQ6msf+IuC1GFQZtWKmBlc+SvRhgkPH3Byk9DF5D+YQV/cSqQoF03h9SqX6+ZtTxGsMU/WJCVFEdCCly696qbhq3qY0IDFwtsRfENbA2x204U/pq/++QSB+pApWY96uB4DbzAQtijzII1EW864mm1RJ1mgfbR8JTysF2GMkorsLwL59nVkJvjTa57M9XF48CMsVLyiv82l6Ujf1/2/pHSrqgn6oESnhEpYg8ofFfwy5XPtqd0VUaLHsURQ4RWTwntvlZ4sARIZxJofPK02EgUNGdZCzVTzRZUUoXW0j6K/+XCAypGI0ptAilx/96+qLhqMWyvWvuU7rBsQXZaqFRbO2/Yziz/Zr6/6AZJmZLewI/P+594VjYa+lquDY/mDq8tSvxDJ0B/z7bWihwwql/DLR3hIiMcHdET/jKoN4bFMdpn2aeq0pXVEy2gp5dx58Kvgfnjw0yiEfJbAlvvIpLuUWOz8bVgru8ZLUc/5N3Mrd4lc7KBBHG6yDDpzsTmOJbdQ=
  template:
    metadata:
      name: app-secret
      namespace: whoapp
