---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secret
  namespace: whoapp
spec:
  encryptedData:
    password: AgAfYl/WwiKJ3MBLDFqHJdJ2E7dQCOHZ4j2i4lkZkcpWiO+fVVFR0dp2Sukf5F4lSyUiyZfQd65owLEfGA2s6FpkSeKVqnOeXEgKOZfdJRvuz0USbhRiq9PkzI5x0oO1RPpEFaOqKEjQDqr1oPSfWrXaXHSeSg4Cn4g4gMwwP7k4nQCtbxtSL/bXXwGm3vZNePA1LKvNu2OQPGWxMjhhgSZyve2P8cmnVxPisphZ6jB9lWV0cAKBpqUvTq7EgcFvsVTKbvljVSyP8POGjtjN1Q/yL7d+iolYpwU/4bn2Xhm/0paqbONL41NiEjMFIT14ub5pXU2eT4R8JaeiE+HBbApjCeg0nqepMQtJg8s14dcTnU3DtU3K1y4icdQPtZqnuQ71vEXHTfxszVKyki8lDquCnaGbopmWH9NhD9HhieqvS1AhaBZOdTYC8nmOjM3nbqRmguoBxLBm2nMOOupzFcJPOLQtBUVhQ8MC6LAdAJ6sSwueYdYvHOm/wy8ESOCWDnEqkguckeCW8llxSvMxhlcMABNoUM/kY8QkRbnwCrUk3ohVR93ZOgA9aL80uD9zBHYLkv1bwJPeZaTIkZVQpZsZ8HUxh3mar7XtYm2tOsqRIBxcnrmLba4wZHXgbc4+avuREs78pkcxPCE0Jc1nIviQAY5nrXZVNtpjqFkt4qS2x6JFmSI0u7DuJWL7KXVIEn2gANQ+RyVxjg==
    username: AgB/A8+GlBYkkdcFkWGxurSgEoiTHnLWPY4zbkk0oDKp5FrWR2AenkLzy3di3bobqyfzplRoIdDme3ppAn3/X/ZlVN/1rlHrkOVYOW8BVTN3VasoIaK0kJS8TwjRDe9M+QS0nNMDbnSVXYpSYfkZ5t7GlkGnSJBE+pcc1P6F20f/kr+k/1TajCjPu/hkE/XL5xhRcZFycVm8MsztmT3XNaA3JdIQSyBxg8zIV74gRu9MFCnFZswPGRfq8dYS98CHmEAfjfd5TizADgx5OMrQhR1ITarQa20FjGf+cSgZw63LMlWnbfW2fVjMi+d/M7jDK8EkwoHIYE/2qTolL3JtQXhosLAlydu30Vt6ggxw1eisP1jRvMe3nQJy2/EjMsgBVcBMbA1NELJFVOmk1Rbb7YXZvP4vLpu1uZ/oheV/wWUsMm9T4ifCTBjCqhPe3pRiAuHvSdRhe4+ZgMl2zxhpqgtTfbDtE4tsoCWymChPSkMwQvpwp+xQ7MuG+NC0rpeqrSYHNrtttx4f+5JxunJbJ7s+7hYFKIL+AJ4fFRhfnrfOAcz8tMmv8TxBCViMxZFuzhSN9260C3MxAZuRKy9O18RTT7HmNBDo/CFz4/JsiKSustBjumLARTLu/ICFu9H8ysRZTSlLy6d0VRM9SqlaHW2UPSxGxFZEK1dEAx5zsrWPWRZmq3fN0YO8PSVpMoXDw0k3blw=
  template:
    metadata:
      name: app-secret
      namespace: whoapp
